/* Blog post metadata, newest first.
   Used by main.js (index blog grid) and post-extras.js (prev/next navigation).
   Hrefs are relative to the site root. */
window.blogPosts = [
  { title: "Fitting a Second Brain Into 8,192 Tokens", description: "Context engineering for my first iOS app: an on-device AI second brain where search never calls the LLM and a test suite bans networking.", href: "docs/blog/2026/atlas-context-engineering.html", date: "2026-07-12", category: "On-Device AI", readingTime: "13 min" },
  { title: "Zero to Deployed on a €0 Bill: Teaching Cloud to TU Delft Students", description: "Nine exercises from FastAPI to auto-deploy, engineered to fit entirely inside free tiers. No credit cards, no leaked service-account keys.", href: "docs/blog/2026/teaching-cloud-tu-delft.html", date: "2026-07-10", category: "Teaching", readingTime: "8 min" },
  { title: "Home Assistant on Kubernetes: A Questionable Decision I'd Make Again", description: "hostNetwork confessions, a busybox init container doing GitOps diplomacy, and a Matter sidecar that finally justifies the pattern.", href: "docs/blog/2026/home-assistant-k8s.html", date: "2026-06-28", category: "Homelab", readingTime: "8 min" },
  { title: "Teaching an AI Agent to Read Receipts (and Politely Decline Your Netflix Subscription)", description: "An agentic expense assistant in production: vision parsing, a submit gate the model can't talk its way past, and 25 conversations as a test suite.", href: "docs/blog/2026/receipt-agent.html", date: "2026-06-14", category: "AI Agents", readingTime: "11 min" },
  { title: "I Built a 2-Day Course on AI Agents. The Agents Were the Easy Part.", description: "Designing 11 modules around a fictional coffee company, three kinds of graders, and why evaluation is where the course pivots.", href: "docs/blog/2026/agent-course.html", date: "2026-05-10", category: "AI Agents", readingTime: "10 min" },
  { title: "My Home Runs on Git Push", description: "k3s on a NUC, Argo CD with selfHeal on, and the discipline I couldn't maintain by willpower. So the cluster maintains it for me.", href: "docs/blog/2026/home-cluster-gitops.html", date: "2026-04-19", category: "Homelab", readingTime: "9 min" },
  { title: "Terraform, GKE, and the 150-Millisecond Question", description: "Three Terraform stacks, a second cluster whose only job is violence, and the two latency fixes only load testing could find.", href: "docs/blog/2026/terraform-load-testing.html", date: "2026-03-22", category: "Infrastructure", readingTime: "10 min" },
  { title: "One Encoder, Three Jobs: Multi-Task NLP for E-commerce Search", description: "Domain-adapting BERT for search queries, sharing encoder layers across three tasks, and the eight F1 points synthetic data quietly cost.", href: "docs/blog/2026/intent-classifier-training.html", date: "2026-03-08", category: "ML Engineering", readingTime: "10 min" },
  { title: "The Minecraft Server That Kills Itself (to Save Me Money)", description: "A world that never stops existing on a server that usually doesn't: RCON polling, a self-terminating VM, and a one-button Cloud Run doorbell.", href: "docs/blog/2026/minecraft-server-killswitch.html", date: "2026-01-25", category: "Cloud", readingTime: "8 min" },
  { title: "The Day I Learned Why Webhooks Need HMAC", description: "From a token in a header to signed requests with replay protection. What one small integration taught me about webhook security.", href: "docs/blog/2025/webhook-hmac.html", date: "2025-12-05", category: "Security", readingTime: "8 min" }
];
